export const GET_WEATHER = 'GET_WEATHER';
export const GET_WEATHER_FULFILLED = 'GET_WEATHER_FULFILLED';
export const GET_WEATHER_REJECTED = 'GET_WEATHER_REJECTED';
export const CHANGE_CITY = 'CHANGE_CITY';
