export const FETCH_WEATHER = 'FETCH_WEATHER';
export const FETCH_WEATHER_FULFILLED = 'FETCH_WEATHER_FULFILLED';
export const FETCH_WEATHER_REJECTED = 'FETCH_WEATHER_REJECTED';
export const CHANGE_CITY = 'CHANGE_CITY';
export const UPDATE_HISTORY = 'UPDATE_HISTORY';
